environment:
  matrix:
    - platform: x86
      PYTHON: C:\Python33
      PYSVN_SETUP_FILE: py33-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49525/%PYSVN_SETUP_FILE%
    - platform: x86
      PYTHON: C:\Python34
      PYSVN_SETUP_FILE: py34-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49529/%PYSVN_SETUP_FILE%
    - platform: x86
      PYTHON: C:\Python35
      PYSVN_SETUP_FILE: py35-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49534/%PYSVN_SETUP_FILE%
    - platform: x64
      PYTHON: C:\Python35-x64
      PYSVN_SETUP_FILE: py35-pysvn-svn194-1.9.3-1884-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49535/%PYSVN_SETUP_FILE%

init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  # Push Python on Path
  set Path=%PYTHON%;%Path%

install:
  # download pysvn setup file
  - mkdir pysvn
  - curl -fsSL -m 300 -o pysvn\%PYSVN_SETUP_FILE% %PYSVN_DL_LINK%

  # create up to date virtual env and install packages
  - python -m venv virtual_env
  - virtual_env\Scripts\activate.bat
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools wheel pathlib2
  - pip list

build_script:
  # build wheel package
  - python setup.py bdist_wheel

on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
