environment:
  matrix:
    - platform: x86
      PY_VER: 27
      PYSVN_SETUP_FILE: py27-pysvn-svn1816-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49516/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 27
      PYSVN_SETUP_FILE: py27-pysvn-svn194-1.9.3-1884-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49519/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 33
      PYSVN_SETUP_FILE: py33-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49525/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 34
      PYSVN_SETUP_FILE: py34-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49529/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 35
      PYSVN_SETUP_FILE: py35-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49534/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 35-x64
      PYSVN_SETUP_FILE: py35-pysvn-svn194-1.9.3-1884-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49535/%PYSVN_SETUP_FILE%

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  # Push Python on Path
  - set Path=C:\Python%PY_VER%;%Path%

install:
  # Download pysvn setup file
  - mkdir pysvn
  - curl -fsSL -m 300 -o pysvn\%PYSVN_SETUP_FILE% %PYSVN_DL_LINK%

  # Install pip which isn't part of Python 3.3.
  - if %PY_VER% EQU 33 (
      curl -fsSL -m 300 -o get-pip.py https://bootstrap.pypa.io/get-pip.py &&
      python get-pip.py
    )

  # Create virtual environment
  - if %PY_VER% GEQ 30 (
      python -m venv env
    ) else (
      virtualenv env
    )
  - env\Scripts\activate.bat

  # Install packages necessary for build
  - pip install --upgrade setuptools wheel
  # Compatible pathlib is only shipped with Python 3.5. Older Python versions have to use the
  # backport pathlib2.
  - if %PY_VER% LSS 35 (
      pip install pathlib2
    )

  - pip list

build_script:
  # build wheel package
  - python setup.py bdist_wheel

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
