environment:
  matrix:
    - platform: x86
      PY_VER: 27
      PYSVN_SETUP_FILE: py27-pysvn-svn1100-1.9.6-1961-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49578/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 27-x64
      PYSVN_SETUP_FILE: py27-pysvn-svn1100-1.9.6-1961-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49579/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 33
      PYSVN_SETUP_FILE: py33-pysvn-svn1100-1.9.6-1961-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49590/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 34
      PYSVN_SETUP_FILE: py34-pysvn-svn1100-1.9.6-1961-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49593/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 35
      PYSVN_SETUP_FILE: py35-pysvn-svn1100-1.9.6-1961-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49599/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 35-x64
      PYSVN_SETUP_FILE: py35-pysvn-svn1100-1.9.6-1961-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49600/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 36
      PYSVN_SETUP_FILE: py36-pysvn-svn1100-1.9.6-1961-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49608/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 36-x64
      PYSVN_SETUP_FILE: py36-pysvn-svn1100-1.9.6-1961-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49609/%PYSVN_SETUP_FILE%

  PATH: C:\Python%PY_VER%;C:\Python%PY_VER%\Scripts;%PATH%

install:
  - curl -fsSL -m 300 --create-dirs -o pysvn/%PYSVN_SETUP_FILE% %PYSVN_DL_LINK%

  - pip install --upgrade setuptools wheel
  # pathlib was introduced with Python 3.4. Older Python versions have to use the backport pathlib2.
  - if %PY_VER% LSS 34 (
      pip install pathlib2
    )
  - pip list

build_script:
  - python setup.py bdist_wheel

artifacts:
  - name: wheel
    path: 'dist\*.whl'

deploy:
  description: 'Wheels for pysvn $(appveyor_repo_tag_name) release'
  provider: GitHub
  auth_token:
    secure: xRVb4JRgTd5AqmwNMPJmCA0NAwbLA6aDZm9irH3PsvXQHAFb7vMDJ0dF9Ua2+qMd
  artifact: wheel
  force_update: true
  on:
    appveyor_repo_tag: true
