platform: x64

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  - set PYTHON=C:\\Python35-x64

install:
  # download pysvn setup file
  - mkdir pysvn
  - curl %CURL_ARGS% -o pysvn\py35-pysvn-svn194-1.9.3-1884-Win64.exe http://tigris.org/files/documents/1233/49535/py35-pysvn-svn194-1.9.3-1884-Win64.exe
  # Put Python on path
  - set PATH=%PATH%;%PYTHON%

  # create up to date virtual env and install packages
  - %PYTHON%\python -m venv virtual_env
  - virtual_env\Scripts\activate.bat
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools wheel
  - pip list

build_script:
  # build wheel package
  - python setup.py bdist_wheel

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
