environment:
  matrix:
    - platform: x86
      PY_VER: 27
      PYSVN_SETUP_FILE: py27-pysvn-svn1816-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49516/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 27-x64
      PYSVN_SETUP_FILE: py27-pysvn-svn194-1.9.3-1884-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49519/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 33
      PYSVN_SETUP_FILE: py33-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49525/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 34
      PYSVN_SETUP_FILE: py34-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49529/%PYSVN_SETUP_FILE%
    - platform: x86
      PY_VER: 35
      PYSVN_SETUP_FILE: py35-pysvn-svn194-1.9.3-1884-Win32.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49534/%PYSVN_SETUP_FILE%
    - platform: x64
      PY_VER: 35-x64
      PYSVN_SETUP_FILE: py35-pysvn-svn194-1.9.3-1884-Win64.exe
      PYSVN_DL_LINK: http://tigris.org/files/documents/1233/49535/%PYSVN_SETUP_FILE%

  PATH: C:\Python%PY_VER%;C:\Python%PY_VER%\Scripts;%PATH%

install:
  - curl -fsSL -m 300 --create-dirs -o pysvn/%PYSVN_SETUP_FILE% %PYSVN_DL_LINK%

  - pip install --upgrade setuptools wheel
  # pathlib was introduced with Python 3.4. Older Python versions have to use the backport pathlib2.
  - if %PY_VER% LSS 34 (
      pip install pathlib2
    )
  - pip list

build_script:
  - python setup.py bdist_wheel

artifacts:
  - name: wheel
    path: 'dist\*.whl'

deploy:
  release: v$(appveyor_repo_tag_name)
  description: 'Wheels for pysvn $(appveyor_repo_tag_name) release'
  provider: GitHub
  auth_token:
    secure: 13qphbT8UNTvkS6LKClYmu5kJTSLG1c1cNtCDr95nXCElqu/YHw5CfZcSoApgOqR
  artifact: wheel
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
